[package]
name = "logos_core"
version = "0.1.0"
edition = "2021"

[features]
idl-build = ["anchor-lang/idl-build"]


[lib]
crate-type = ["cdylib", "lib"]
name = "logos_core"

[dependencies]
anchor-lang = "0.32.1"
